# Generated by Django 6.0.4 on 2026-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
