# Generated by Django 6.0.4 on 2026-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
